export const CollectibleNameCollection: { [index: string]: string } = {
	"1": "Diamond Vault",
	"2": "Myers Vault",
	"3": "Black Vault",
	"4": "Sapphire Mystery Box",
	"5": "Gold Mystery Box",
	"6": "Diamond Mystery Box",
	"7": "Vencetti Supper Dress",
	"8": "Timberwater",
	"9": "Terror Heist Mask",
	"10": "Bike Tech Fleece",
	"11": "Lucci Designer Collection",
	"12": "Hype Bomber Jacket",
	"13": "Baller Design Tee",
	"14": "Helix Space Suit",
	"15": "Helix Chain",
	"16": "Gold Watch",
	"17": "Clout Glasses",
	"18": "Bay Rans",
	"19": "Diamond Chain",
	"20": "Pimpin Shades",
	"21": "Bauhaus Force",
	"22": "Hyde Defiant",
	"23": "Henry H-160",
	"24": "Bauhaus Wagen",
	"25": "Medusa M1",
	"26": "Prancer 116",
	"27": "Rambo Auroch",
	"28": "N75 Streamline",
	"29": "Edison Hypertruck",
	"30": "Burreti Meteor",
	"31": "Ferocious Z1",
	"32": "Bauhaus F1",
	"33": "T1 Tank",
	"34": "Predator Jet",
	"35": "Poseidon Yacht"
}
